HealthAppFrontend/Controllers/ClinicalSpecialtyFrontController.cs
using HealthAppFrontend.DataRepository.IDataRepository;
using HealthAppFrontend.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sweetalert.Controllers;
using sweetalert.Models;
using System;
using System.Threading.Tasks;

namespace HealthAppFrontend.Controllers
{
    public class ClinicalSpecialtyFrontController : BaseController
    {

        private readonly IClinicalSpecialtyRepository _clinicalSpecialtyRepository;

        public ClinicalSpecialtyFrontController(IClinicalSpecialtyRepository clinicalSpecialtyRepository)
        {
            _clinicalSpecialtyRepository = clinicalSpecialtyRepository;
        }
        // GET: ClinicalSpecialtyFrontController
        public new async Task<ActionResult> Index()
        {
            string UrlWebApi = "http://localhost:20495/specialties";
            return View(await _clinicalSpecialtyRepository.GetAllAsync(UrlWebApi));
        }

        // GET: ClinicalSpecialtyFrontController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            string UrlWebApi = $"http://localhost:20495/specialties/{id}";
            return View(await _clinicalSpecialtyRepository.GetByIdAsync(UrlWebApi));
        }


        //GET: ClinicalSpecialtyFrontController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ClinicalSpecialtyFrontController/Create

        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(ClinicalSpecialtyFront newClinicalSpecialty)
        {
            try
            {
                string UrlWebApi = "http://localhost:20495/specialties";
                await _clinicalSpecialtyRepository.InsertAsync(UrlWebApi, newClinicalSpecialty);
                //Notify("Se ha creado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No ha sido posible crear", notificationType: NotificationType.error);
                return View();
            }
        }

        // GET: ClinicalSpecialtyFrontController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ClinicalSpecialtyFrontController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, ClinicalSpecialtyFront editClinicalSpecialty)
        {
            try
            {
                string UrlWebApi = $"http://localhost:20495/specialties/{id}";
                await _clinicalSpecialtyRepository.UpdateAsync(UrlWebApi, editClinicalSpecialty);
                //Notify("Se ha actualizado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No ha sido posible actualizar", notificationType: NotificationType.error);
                return View();
            }
        }

        // GET: ClinicalSpecialtyFrontController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ClinicalSpecialtyFrontController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, ClinicalSpecialtyFront clinicalSpecialtyToDelete)
        {
            try
            {
                string UrlWebApi = $"http://localhost:20495/specialties/{clinicalSpecialtyToDelete.id}";                
                var response = await _clinicalSpecialtyRepository.DeleteAsync(UrlWebApi);
                //Notify("Se ha eliminado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No se ha podido eliminar la especialidad debido a una dependencia", notificationType: NotificationType.error);
                return View();
            }
        }
    }
}

HealthAppFrontend/Controllers/DoctorFrontController.cs
using HealthAppFrontend.DataRepository.IDataRepository;
using HealthAppFrontend.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sweetalert.Controllers;
using sweetalert.Models;
using System.Threading.Tasks;

namespace HealthAppFrontend.Controllers
{
    public class DoctorFrontController : BaseController
    {

        private readonly IDoctorFrontRepository _doctorFrontRepository;

        public DoctorFrontController(IDoctorFrontRepository doctorFrontRepository)
        {
            _doctorFrontRepository = doctorFrontRepository;
        }
        // GET: DoctorFrontController
        public async Task<ActionResult> Index()
        {
            string UrlWebApi = "http://localhost:20495/doctores";
            return View(await _doctorFrontRepository.GetAllAsync(UrlWebApi));
        }

        // GET: DoctorFrontController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            string UrlWebApi = $"http://localhost:20495/doctores/{id}";
            return View(await _doctorFrontRepository.GetByIdAsync(UrlWebApi));
        }

        // GET: DoctorFrontController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DoctorFrontController/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(RichDoctorFront richDoctorFront)
        {
            try
            {
                string UrlWebApi = "http://localhost:20495/doctores";
                await _doctorFrontRepository.InsertAsync(UrlWebApi, richDoctorFront);
                //Notify("Se ha creado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No ha sido posible crear", notificationType: NotificationType.error);
                return View();
            }
        }

        // GET: DoctorFrontController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: DoctorFrontController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, RichDoctorFront richDoctorFront)
        {
            try
            {
                string UrlWebApi = $"http://localhost:20495/doctores/{id}";
                await _doctorFrontRepository.UpdateAsync(UrlWebApi, richDoctorFront);
                //Notify("Se ha actualizado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No ha sido posible actualizar", notificationType: NotificationType.error);
                return View();
            }
        }

        // GET: DoctorFrontController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: DoctorFrontController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, RichDoctorFront richDoctorFront)
        {
            try
            {
                string UrlWebApi = $"http://localhost:20495/doctores/{richDoctorFront.id}";
                var response = await _doctorFrontRepository.DeleteAsync(UrlWebApi);
                //Notify("Se ha eliminado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No se ha podido eliminar el doctor", notificationType: NotificationType.error);
                return View();
            }
        }
    }
}

HealthAppFrontend/Controllers/MedicalCenterFrontController.cs
using HealthAppFrontend.DataRepository.IDataRepository;
using HealthAppFrontend.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using sweetalert.Controllers;
using sweetalert.Models;
using System.Threading.Tasks;

namespace HealthAppFrontend.Controllers
{
    public class MedicalCenterFrontController : BaseController
    {

        private readonly IMedicalCenterRepository _medicalCenterRepository;
        
        public MedicalCenterFrontController(IMedicalCenterRepository medicalCenterRepository)
        {
           _medicalCenterRepository = medicalCenterRepository;
        }

        // GET: MedicalCenterFrontController
        public async Task<ActionResult> Index()
        {
            string UrlWebApi = "http://localhost:20495/centers";
        
            return View(await _medicalCenterRepository.GetAllAsync(UrlWebApi));
        }

        // GET: MedicalCenterFrontController/Details/5
        public async Task<ActionResult> Details(int id)
        {
            string UrlWebApi = $"http://localhost:20495/centers/{id}";
            return View(await _medicalCenterRepository.GetByIdAsync(UrlWebApi));
        }

        // GET: MedicalCenterFrontController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: MedicalCenterFrontController/Create
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Create(MedicalCenterFront newMedicalCenter)
        {
            try
            {
                string UrlWebApi = "http://localhost:20495/centers";
                await _medicalCenterRepository.InsertAsync(UrlWebApi, newMedicalCenter);
                //Notify("Se ha creado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No ha sido posible crear", notificationType: NotificationType.error);
                return View();
            }
        }

        // GET: MedicalCenterFrontController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: MedicalCenterFrontController/Edit/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, MedicalCenterFront medicalCenterFront)
        {
            try
            {
                string UrlWebApi = $"http://localhost:20495/centers/{id}";
                await _medicalCenterRepository.UpdateAsync(UrlWebApi, medicalCenterFront);
                //Notify("Se ha actualizado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No ha sido posible actualizar", notificationType: NotificationType.error);
                return View();
            }
        }

        // GET: MedicalCenterFrontController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: MedicalCenterFrontController/Delete/5
        [HttpPost]
        //[ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, MedicalCenterFront medicalCenterFront)
        {
            try
            {
                string UrlWebApi = $"http://localhost:20495/centers/{medicalCenterFront.id}";
                var response = await _medicalCenterRepository.DeleteAsync(UrlWebApi);
                //Notify("Se ha eliminado correctamente", notificationType: NotificationType.success);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                //Notify("No se ha podido eliminar el centro medico debido a una dependencia", notificationType: NotificationType.error);
                return View();
            }
        }
    }
}

HealthAppFrontend/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HealthApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HealthApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>*@

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="DoctorFront" asp-action="Index">Doctores</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalCenterFront" asp-action="Index">Centros Médicos</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="ClinicalSpecialtyFront" asp-action="Index">Especialidades</a>
                        </li>

                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>*@

                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HealthApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

HealthAppFrontend/Views/Shared/_notificationPartial.cshtml
<script>

	var msg = @(TempData["Message"] != null ? Html.Raw(TempData["Message"]) : Html.Raw("undefined"));


	if (msg)
	{
		if(msg.provider == "sweetAlert")
		{
			swal.fire({
				title: msg.title,
				text: msg.text,
				icon: msg.icon
			});
		} else {
			toastr[msg.type](msg.text, msg.title)
		}
	}
</script>